language: php
sudo: false

matrix:
  fast_finish: true
  include:
    - php: "5.2"
      env: USE_PSALM=0
           CHECK_MBSTRING=1
      dist: precise
    - php: "5.3"
      env: USE_PSALM=0
           CHECK_MBSTRING=1
      dist: precise
    - php: "5.4"
      env: USE_PSALM=0
           CHECK_MBSTRING=1
    - php: "5.5"
      env: USE_PSALM=0
           CHECK_MBSTRING=1
    - php: "5.6"
      env: USE_PSALM=1
           CHECK_MBSTRING=1
    - php: "7.0"
      env: USE_PSALM=1
           CHECK_MBSTRING=1
    - php: "7.1"
      env: USE_PSALM=1
           CHECK_MBSTRING=1
    - php: "7.2"
      env: USE_PSALM=1
           CHECK_MBSTRING=0
    - php: "nightly"
      env: USE_PSALM=1
           CHECK_MBSTRING=0
    - php: "master"
      env: USE_PSALM=1
           CHECK_MBSTRING=0
    - php: "hhvm"
      env: USE_PSALM=1
           CHECK_MBSTRING=1
  allow_failures:
    - php: "master"
    - php: "hhvm"

install:
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.2" ]]; then `phpenv global 5.3`; fi
    - composer self-update
    - if [[ $USE_PSALM -eq 1 ]]; then composer require --dev "vimeo/psalm:dev-master"; fi
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.2" ]]; then composer require "xrstf/composer-php52:1.*"; fi
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.2" ]]; then composer require --dev "phpunit/phpunit-php52:dev-3.6.12-php52"; fi
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.2" ]]; then composer require --dev "phpunit/phpunit-mock-objects-php52:dev-1.1.0-php52"; fi
    - composer update
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.2" ]]; then `phpenv global "$TRAVIS_PHP_VERSION"`; fi

script:
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.2" ]]; then travis_wait 30 vendor/bin/phpunit-php52; exit 0; fi
    - travis_wait 30 vendor/bin/phpunit
    - if [[ $CHECK_MBSTRING -eq 1 ]]; then php -dmbstring.func_overload=7 vendor/bin/phpunit; fi
    - vendor/bin/phpunit --bootstrap autoload-fast.php
    - if [[ $CHECK_MBSTRING -eq 1 ]]; then php -dmbstring.func_overload=7 vendor/bin/phpunit --bootstrap autoload-fast.php; fi
    - if [[ $USE_PSALM -eq 1 ]]; then vendor/bin/psalm; fi
